import type { Metadata } from "next";
import localFont from "next/font/local";

import { Footer } from "@/components/footer/Footer";
import { Header } from "@/components/header/Header";
import "./globals.css";
import React from "react";

const poppinsRegular = localFont({
  src: "../../public/fonts/Poppins-Regular.otf",
  variable: "--poppins-regular",
});
const poppinsBold = localFont({
  src: "../../public/fonts/Poppins-Bold.otf",
  variable: "--poppins-bold",
});
const poppinsSemiBold = localFont({
  src: "../../public/fonts/Poppins-SemiBold.otf",
  variable: "--poppins-semi-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>):React.ReactElement {
  return (
    <html lang="en">
      <body className={`${poppinsRegular.variable} ${poppinsBold.variable} ${poppinsSemiBold.variable} antialiased`}>
        <section className="max-w-[1024px] mx-auto min-h-screen flex flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </section>
      </body>
    </html>
  );
}
